name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t python-server
          docker save -o my-python-server.tar my-python-server

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-python-server
          path: my-python-server.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-python-server
          path: .

      - name: Run Docker container
        run: |
          docker load -i my-python-server.tar
          docker run -d -p 8000:8000 my-python-server
