name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Python version
        run: python --version

      - name: Start server
        run: |
          python server.py &
          sleep 5

      - name: Check if server is running
        run: curl -I http://localhost:8000

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy step here...
        run: echo "Deploy step here..."
