name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python --version

      - name: Start server in background
        run: |
          python server.py &
          sleep 5

      - name: Check if server is running
        run: curl -I http://localhost:8000

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy step
        run: echo "Deploy step here..."
